// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LockAiAPI.Data;

#nullable disable

namespace LockAiAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCCApi.Models.Objeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataAtualizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataInclusao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioAtualizacao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int");

                    b.Property<string>("LocalidadePrimaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadeSecundaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadeTercearia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idTipoObjeto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_OBJETOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = "2025-06-21",
                            DataInclusao = "2025-06-20",
                            Descricao = "Mesa de madeira",
                            IdUsuarioAtualizacao = 100,
                            IdUsuarioInclusao = 100,
                            LocalidadePrimaria = "Predio A",
                            LocalidadeSecundaria = "Andar 1",
                            LocalidadeTercearia = "Sala 101",
                            Nome = "Mesa",
                            Situacao = "Ativa",
                            idTipoObjeto = 1
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = "2025-06-20",
                            DataInclusao = "2025-06-18",
                            Descricao = "Cadeira ergonômica para escritório",
                            IdUsuarioAtualizacao = 101,
                            IdUsuarioInclusao = 101,
                            LocalidadePrimaria = "Prédio B",
                            LocalidadeSecundaria = "Andar 2",
                            LocalidadeTercearia = "Sala 205",
                            Nome = "Cadeira",
                            Situacao = "Em uso",
                            idTipoObjeto = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
